defaults:
  - _self_
  - data_processing_config_schema
  - dataset_reader_manager: ghc_jigsaw_twitter
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

version: v7