defaults:
 - dataset_cleaner_manager_schema
 
 - dataset_cleaner@dataset_cleaners.stop_words: stop_words_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.to_lower_case: to_lower_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.url: url_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.punctuation: punctuation_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.non_letters: non_letter_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.non_ascii: non_ascii_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.reference: reference_to_account_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.re_tweet: retweet_dataset_cleaner_schema
 - dataset_cleaner@dataset_cleaners.spell_correction: spell_correction_dataset_cleaner_schema
